//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStokTakipSistemi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TBLMUSTERI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLMUSTERI()
        {
            this.TBLSATIS = new HashSet<TBLSATIS>();
        }
    
        public int MUSTERIID { get; set; }
        [Required(ErrorMessage ="Müþteri adý boþ býrakýlamaz.")]
        [MinLength(3,ErrorMessage ="Müþteri adý en az 3 karakter olmalýdýr.")]
        [MaxLength(30,ErrorMessage ="Müþteri adý en fazla 30 karakter uzunluðunda olmalýdýr.")]
        public string MUSTERIAD { get; set; }
        [Required(ErrorMessage = "Müþteri soyadý boþ býrakýlamaz.")]
        [MinLength(3, ErrorMessage = "Müþteri soyadý en az 3 karakter olmalýdýr.")]
        [MaxLength(30, ErrorMessage = "Müþteri soyadý en fazla 30 karakter uzunluðunda olmalýdýr.")]
        public string MUSTERISOYAD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSATIS> TBLSATIS { get; set; }
    }
}
