//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStokTakipSistemi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBLSATIS
    {
        public int SATISID { get; set; }
        public Nullable<int> URUN { get; set; }
        public Nullable<int> MUSTERI { get; set; }

        [Required(ErrorMessage ="Adet miktarý boþ býrakýlamaz.")]
        public Nullable<byte> ADET { get; set; }

        [Required(ErrorMessage ="Satýþ fiyatý boþ býrakýlamaz.")]
        public Nullable<decimal> SATISFIYAT { get; set; }
        public virtual TBLMUSTERI TBLMUSTERI { get; set; }
        public virtual TBLURUN TBLURUN { get; set; }
    }
}
